### ISSUE TITLE
some koa2/koa problem

### ISSUE THREAD

**Issue by fengyun2** [Lxxyx/koa2-easy#1]
您好,请问在 `koa2` 中的 `controller` 和 `model` 层, 如何用 `es6` 的 `class方式(面向对象)` 改写而不是使用  `面向过程`  的方式书写。

**Comment by Lxxyx** [comment]
@fengyun2 你好，感谢你对koa2-easy的支持。
关于controller 和 model 层, 如何用 es6 的 class方式改写。
这儿我认为并没有什么必要。具体可以参见mongoose的model。改写与否差别不大。

**Comment by angelyu2014** [comment]
koa2-alertTemplate模块下的index modeule.exprots=function(,ext = '.html') 这里编译不通过
