### ISSUE TITLE
请问咱们的项目演示地址部署在哪里？

### ISSUE THREAD

**Issue by hezhongfeng** [Lxxyx/koa2-easy#2]
以这个项目为模板做了个仿cnode的网站
想部署到云服务器上
请问有这方面的推荐吗？

**Comment by Lxxyx** [comment]
国内的话，阿里云或者腾讯云。
国外的话，DigitOcean或者linode。

**Comment by hezhongfeng** [comment]
@Lxxyx 
请问你演示的是部署在什么上的？

**Comment by Lxxyx** [comment]
@hezhongfeng 腾讯云。

**Comment by hezhongfeng** [comment]
@Lxxyx 
谢谢
