### ISSUE TITLE
请问bluebird这个模块的作用

### ISSUE THREAD

**Issue by hezhongfeng** [Lxxyx/koa2-easy#3]
我看只是`global.Promise = require('bluebird')`应该是在全局变量下引用了
这个模块是给babel使用的吗？
如果是给它使用的就不看了，因为以后也许就不需要babel转化了

**Comment by Lxxyx** [comment]
之所以用bluebird作为全局的Promise，是因为bluebird的promise性能比原生的要高。
在这儿替换有利于提高性能。

**Comment by hezhongfeng** [comment]
这样啊
就是说我在一个函数里使用promise包装一个异步操作的话这个Promise会比原生提供的好呗？

**Comment by Lxxyx** [comment]
应该说的bluebird这个Promise库提供的Promise，比原生性能高。

**Comment by hezhongfeng** [comment]
谢谢解释
跟着你这个项目学到了很多
也在此基础上做了点东西
非常感谢

**Comment by Lxxyx** [comment]
@hezhongfeng 客气了。继续加油~
