### ISSUE TITLE
关于ejs使用问题

### ISSUE THREAD

**Issue by MinosIE** [Lxxyx/koa2-easy#5]
求问大神此框架是否支持ejs?
我在app.js里面增加配置
app.use(views(__dirname + '/views', {
  extension: 'ejs'
}))
页面index.ejs里面调用
<%= title %>
后台报错：
Unhandled rejection Error: Can't set headers after they are sent.

**Comment by hezhongfeng** [comment]
这个模板都是ejs的
你的报错应该跟ejs的使用没关系
建议你重新下载这个模板使用

**Comment by Lxxyx** [comment]
和ejs没关系的，你可以搜索一下：Can't set headers after they are sent或者贴出你的代码

**Comment by MinosIE** [comment]
@hezhongfeng @Lxxyx 是我的配置有问题 已经解决了 多谢二位
